import os
from pathlib import Path

def create_sar_audit_structure():
    # Define the root directory
    root = Path("sar-audit-engine")
    
    # Define the directory structure and the files within them
    structure = {
        "data/raw": ["accounts.csv", "transactions.csv", "alerts.csv"],
        "data/processed/cases": ["case_001.json", "case_002.json"],
        "data/processed/feature_outputs": ["signals_case_001.json"],
        "data/logs": ["audit_logs.json", "reasoning_versions.json"],
        "knowledge/typologies": [
            "layering.txt", "structuring.txt", "smurfing.txt", "funnel_accounts.txt"
        ],
        "knowledge/templates": ["sar_standard.txt", "sar_condensed.txt"],
        "knowledge/regulations": ["reporting_requirements.txt", "narrative_guidelines.txt"],
        "vector_db": ["build_vector_db.py", "retrieval.py"],
        "vector_db/chroma_store": [],  # Directory only (auto-generated by Chroma)
        "core": [
            "case_builder.py", "feature_extractor.py", "reasoning_engine.py", 
            "evidence_mapper.py", "audit_trail.py"
        ],
        "llm": ["prompt_templates.py", "generator.py"],
        "api": ["app.py", "routes.py"],
        "ui": ["dashboard.py"],
        "config": ["settings.py"],
        "tests": ["test_reasoning.py", "test_retrieval.py"],
        ".": ["requirements.txt", "README.md", "main.py"]
    }

    print(f"Creating project structure in: {root.absolute()}")

    for folder, files in structure.items():
        # Create the directory path
        target_dir = root / folder if folder != "." else root
        target_dir.mkdir(parents=True, exist_ok=True)
        
        # Create each file in the directory
        for file_name in files:
            file_path = target_dir / file_name
            file_path.touch(exist_ok=True)
            
    print("\nStructure created successfully!")

if __name__ == "__main__":
    create_sar_audit_structure()
